"""
Seed 20 fully-annotated sample frames into Supabase for end-to-end testing.

Frames are carefully chosen to cover:
  - All 6 face shapes (oval, round, square, heart, diamond, oblong)
  - All 3 undertones (warm, cool, neutral)
  - All 4 retailers (Lenskart, Titan Eye+, John Jacobs, Ray-Ban)
  - All major styles (rectangular, round, oval, square, cat-eye, wayfarer, aviator, browline, geometric, rimless)
  - All price tiers (₹800 – ₹14,000)

product_image_url points to publicly available product images from the retailers.
These URLs may expire — replace with your own R2 URLs after running the scraper.

Usage:
    cd backend
    python db/seed.py
    python db/seed.py --dry-run   # print records without inserting
"""
import sys
import argparse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

SEED_FRAMES = [
    # ── 1. Rectangular | Tortoiseshell | Lenskart ──────────────────────────
    {
        "frame_id": "11111111-0001-0000-0000-000000000001",
        "name": "Vincent Chase VC E14662 C1",
        "style": "rectangular",
        "colour": "tortoiseshell",
        "colour_hex": "#8B5C2A",
        "material": "acetate",
        "face_shape_tags": ["oval", "round", "oblong"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 52,
        "bridge_width_mm": 17,
        "temple_length_mm": 140,
        "vibe_tags": ["classic", "professional"],
        "retailer": "Lenskart",
        "price_inr": 1499,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e14662-c1-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/cache/1/thumbnail/628x301/9df78eab33525d08d6e5fb8d27136e95/v/i/vincent-chase-vc-e14662-c1-eyeglasses.jpg",
    },
    # ── 2. Round | Black | Titan Eye+ ─────────────────────────────────────
    {
        "frame_id": "11111111-0002-0000-0000-000000000002",
        "name": "Titan Eye+ T1203 C1",
        "style": "round",
        "colour": "black",
        "colour_hex": "#1A1A1A",
        "material": "metal",
        "face_shape_tags": ["square", "heart", "oblong"],
        "undertone_tags": ["cool", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 50,
        "bridge_width_mm": 20,
        "temple_length_mm": 145,
        "vibe_tags": ["minimal", "editorial"],
        "retailer": "Titan Eye+",
        "price_inr": 2299,
        "buy_url": "https://www.titaneyeplus.com/product/T1203C1",
        "product_image_url": "https://www.titaneyeplus.com/media/catalog/product/T/1/T1203C1.jpg",
    },
    # ── 3. Cat-eye | Burgundy | John Jacobs ───────────────────────────────
    {
        "frame_id": "11111111-0003-0000-0000-000000000003",
        "name": "John Jacobs JJ E13456 C2",
        "style": "cat-eye",
        "colour": "burgundy",
        "colour_hex": "#800020",
        "material": "acetate",
        "face_shape_tags": ["diamond", "oval", "square"],
        "undertone_tags": ["cool"],
        "gender_tag": "women",
        "lens_width_mm": 50,
        "bridge_width_mm": 18,
        "temple_length_mm": 140,
        "vibe_tags": ["editorial", "bold"],
        "retailer": "John Jacobs",
        "price_inr": 3499,
        "buy_url": "https://www.johnjacobs.com/jj-e13456-c2-eyeglasses.html",
        "product_image_url": "https://static.johnjacobs.com/media/catalog/product/jj-e13456-c2.jpg",
    },
    # ── 4. Browline | Brown | Ray-Ban ──────────────────────────────────────
    {
        "frame_id": "11111111-0004-0000-0000-000000000004",
        "name": "Ray-Ban RB5154 Clubmaster",
        "style": "browline",
        "colour": "brown",
        "colour_hex": "#654321",
        "material": "mixed",
        "face_shape_tags": ["oval", "heart", "diamond"],
        "undertone_tags": ["warm"],
        "gender_tag": "unisex",
        "lens_width_mm": 51,
        "bridge_width_mm": 21,
        "temple_length_mm": 145,
        "vibe_tags": ["retro", "classic", "professional"],
        "retailer": "Ray-Ban",
        "price_inr": 9990,
        "buy_url": "https://www.ray-ban.com/en_IN/p/rb5154-clubmaster/RB5154__2372",
        "product_image_url": "https://www.ray-ban.com/media/catalog/product/R/B/RB5154_2372_001_shad_qt.png",
    },
    # ── 5. Wayfarer | Navy | Lenskart ─────────────────────────────────────
    {
        "frame_id": "11111111-0005-0000-0000-000000000005",
        "name": "Vincent Chase VC E13553 C6",
        "style": "wayfarer",
        "colour": "navy",
        "colour_hex": "#001F5B",
        "material": "acetate",
        "face_shape_tags": ["round", "oblong", "oval"],
        "undertone_tags": ["cool", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 54,
        "bridge_width_mm": 18,
        "temple_length_mm": 145,
        "vibe_tags": ["classic", "bold"],
        "retailer": "Lenskart",
        "price_inr": 1799,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e13553-c6-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e13553-c6.jpg",
    },
    # ── 6. Oval | Rose Gold | John Jacobs ─────────────────────────────────
    {
        "frame_id": "11111111-0006-0000-0000-000000000006",
        "name": "John Jacobs JJ E11234 C3",
        "style": "oval",
        "colour": "rose_gold",
        "colour_hex": "#B76E79",
        "material": "metal",
        "face_shape_tags": ["square", "round", "oblong"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "women",
        "lens_width_mm": 51,
        "bridge_width_mm": 16,
        "temple_length_mm": 140,
        "vibe_tags": ["minimal", "editorial"],
        "retailer": "John Jacobs",
        "price_inr": 4299,
        "buy_url": "https://www.johnjacobs.com/jj-e11234-c3-eyeglasses.html",
        "product_image_url": "https://static.johnjacobs.com/media/catalog/product/jj-e11234-c3.jpg",
    },
    # ── 7. Geometric | Gunmetal | Titan Eye+ ──────────────────────────────
    {
        "frame_id": "11111111-0007-0000-0000-000000000007",
        "name": "Titan Eye+ T3112 C5",
        "style": "geometric",
        "colour": "gunmetal",
        "colour_hex": "#545E6B",
        "material": "metal",
        "face_shape_tags": ["oval", "heart"],
        "undertone_tags": ["cool"],
        "gender_tag": "men",
        "lens_width_mm": 53,
        "bridge_width_mm": 18,
        "temple_length_mm": 145,
        "vibe_tags": ["minimal", "professional"],
        "retailer": "Titan Eye+",
        "price_inr": 3199,
        "buy_url": "https://www.titaneyeplus.com/product/T3112C5",
        "product_image_url": "https://www.titaneyeplus.com/media/catalog/product/T/3/T3112C5.jpg",
    },
    # ── 8. Rimless | Clear | Lenskart ─────────────────────────────────────
    {
        "frame_id": "11111111-0008-0000-0000-000000000008",
        "name": "Vincent Chase VC E15234 C1",
        "style": "rimless",
        "colour": "clear",
        "colour_hex": "#E8E8F0",
        "material": "titanium",
        "face_shape_tags": ["heart", "diamond", "oval"],
        "undertone_tags": ["warm", "cool", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 50,
        "bridge_width_mm": 16,
        "temple_length_mm": 140,
        "vibe_tags": ["minimal"],
        "retailer": "Lenskart",
        "price_inr": 2499,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e15234-c1-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e15234-c1.jpg",
    },
    # ── 9. Square | Tortoiseshell | Ray-Ban ───────────────────────────────
    {
        "frame_id": "11111111-0009-0000-0000-000000000009",
        "name": "Ray-Ban RB5228 Square",
        "style": "square",
        "colour": "tortoiseshell",
        "colour_hex": "#7B4F2C",
        "material": "acetate",
        "face_shape_tags": ["round", "oval"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 55,
        "bridge_width_mm": 17,
        "temple_length_mm": 145,
        "vibe_tags": ["classic", "professional"],
        "retailer": "Ray-Ban",
        "price_inr": 10490,
        "buy_url": "https://www.ray-ban.com/en_IN/p/rb5228/RB5228__2144",
        "product_image_url": "https://www.ray-ban.com/media/catalog/product/R/B/RB5228_2144_001_shad_qt.png",
    },
    # ── 10. Rectangular | Silver | John Jacobs ────────────────────────────
    {
        "frame_id": "11111111-0010-0000-0000-000000000010",
        "name": "John Jacobs JJ E12103 C1",
        "style": "rectangular",
        "colour": "silver",
        "colour_hex": "#C0C0C0",
        "material": "metal",
        "face_shape_tags": ["round", "oblong", "oval"],
        "undertone_tags": ["cool"],
        "gender_tag": "men",
        "lens_width_mm": 54,
        "bridge_width_mm": 17,
        "temple_length_mm": 140,
        "vibe_tags": ["professional", "minimal"],
        "retailer": "John Jacobs",
        "price_inr": 3999,
        "buy_url": "https://www.johnjacobs.com/jj-e12103-c1-eyeglasses.html",
        "product_image_url": "https://static.johnjacobs.com/media/catalog/product/jj-e12103-c1.jpg",
    },
    # ── 11. Aviator | Gold | Lenskart ─────────────────────────────────────
    {
        "frame_id": "11111111-0011-0000-0000-000000000011",
        "name": "Vincent Chase VC E14001 C2",
        "style": "aviator",
        "colour": "gold",
        "colour_hex": "#C8A000",
        "material": "metal",
        "face_shape_tags": ["oval", "heart", "round"],
        "undertone_tags": ["warm"],
        "gender_tag": "unisex",
        "lens_width_mm": 58,
        "bridge_width_mm": 14,
        "temple_length_mm": 135,
        "vibe_tags": ["classic", "bold", "retro"],
        "retailer": "Lenskart",
        "price_inr": 1299,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e14001-c2-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e14001-c2.jpg",
    },
    # ── 12. Round | Amber | Titan Eye+ ────────────────────────────────────
    {
        "frame_id": "11111111-0012-0000-0000-000000000012",
        "name": "Titan Eye+ T4221 C3",
        "style": "round",
        "colour": "amber",
        "colour_hex": "#C89600",
        "material": "acetate",
        "face_shape_tags": ["square", "diamond", "oblong"],
        "undertone_tags": ["warm"],
        "gender_tag": "unisex",
        "lens_width_mm": 49,
        "bridge_width_mm": 20,
        "temple_length_mm": 145,
        "vibe_tags": ["retro", "editorial"],
        "retailer": "Titan Eye+",
        "price_inr": 2699,
        "buy_url": "https://www.titaneyeplus.com/product/T4221C3",
        "product_image_url": "https://www.titaneyeplus.com/media/catalog/product/T/4/T4221C3.jpg",
    },
    # ── 13. Browline | Olive | Lenskart ───────────────────────────────────
    {
        "frame_id": "11111111-0013-0000-0000-000000000013",
        "name": "Vincent Chase VC E16789 C4",
        "style": "browline",
        "colour": "olive",
        "colour_hex": "#6B8E23",
        "material": "mixed",
        "face_shape_tags": ["oval", "diamond"],
        "undertone_tags": ["warm"],
        "gender_tag": "men",
        "lens_width_mm": 52,
        "bridge_width_mm": 19,
        "temple_length_mm": 145,
        "vibe_tags": ["retro", "classic"],
        "retailer": "Lenskart",
        "price_inr": 1899,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e16789-c4-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e16789-c4.jpg",
    },
    # ── 14. Cat-eye | Navy | John Jacobs ──────────────────────────────────
    {
        "frame_id": "11111111-0014-0000-0000-000000000014",
        "name": "John Jacobs JJ E13445 C5",
        "style": "cat-eye",
        "colour": "navy",
        "colour_hex": "#001F5B",
        "material": "acetate",
        "face_shape_tags": ["diamond", "oval"],
        "undertone_tags": ["cool"],
        "gender_tag": "women",
        "lens_width_mm": 51,
        "bridge_width_mm": 17,
        "temple_length_mm": 140,
        "vibe_tags": ["editorial", "bold", "professional"],
        "retailer": "John Jacobs",
        "price_inr": 3799,
        "buy_url": "https://www.johnjacobs.com/jj-e13445-c5-eyeglasses.html",
        "product_image_url": "https://static.johnjacobs.com/media/catalog/product/jj-e13445-c5.jpg",
    },
    # ── 15. Wayfarer | Black | Titan Eye+ ─────────────────────────────────
    {
        "frame_id": "11111111-0015-0000-0000-000000000015",
        "name": "Titan Eye+ T5123 C1",
        "style": "wayfarer",
        "colour": "black",
        "colour_hex": "#1A1A1A",
        "material": "acetate",
        "face_shape_tags": ["round", "oblong", "oval"],
        "undertone_tags": ["cool", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 54,
        "bridge_width_mm": 18,
        "temple_length_mm": 145,
        "vibe_tags": ["classic", "bold"],
        "retailer": "Titan Eye+",
        "price_inr": 2499,
        "buy_url": "https://www.titaneyeplus.com/product/T5123C1",
        "product_image_url": "https://www.titaneyeplus.com/media/catalog/product/T/5/T5123C1.jpg",
    },
    # ── 16. Rectangular | Blue | Ray-Ban ──────────────────────────────────
    {
        "frame_id": "11111111-0016-0000-0000-000000000016",
        "name": "Ray-Ban RB5362 New Wayfarer",
        "style": "rectangular",
        "colour": "blue",
        "colour_hex": "#4169E1",
        "material": "acetate",
        "face_shape_tags": ["round", "oblong", "oval"],
        "undertone_tags": ["cool"],
        "gender_tag": "unisex",
        "lens_width_mm": 55,
        "bridge_width_mm": 18,
        "temple_length_mm": 145,
        "vibe_tags": ["bold", "sporty"],
        "retailer": "Ray-Ban",
        "price_inr": 11490,
        "buy_url": "https://www.ray-ban.com/en_IN/p/rb5362/RB5362__8197",
        "product_image_url": "https://www.ray-ban.com/media/catalog/product/R/B/RB5362_8197_001_shad_qt.png",
    },
    # ── 17. Geometric | Cognac | Lenskart ────────────────────────────────
    {
        "frame_id": "11111111-0017-0000-0000-000000000017",
        "name": "Vincent Chase VC E17234 C5",
        "style": "geometric",
        "colour": "cognac",
        "colour_hex": "#9C6114",
        "material": "acetate",
        "face_shape_tags": ["oval", "heart"],
        "undertone_tags": ["warm"],
        "gender_tag": "unisex",
        "lens_width_mm": 52,
        "bridge_width_mm": 17,
        "temple_length_mm": 140,
        "vibe_tags": ["editorial", "bold"],
        "retailer": "Lenskart",
        "price_inr": 2099,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e17234-c5-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e17234-c5.jpg",
    },
    # ── 18. Oval | Warm Grey | John Jacobs ────────────────────────────────
    {
        "frame_id": "11111111-0018-0000-0000-000000000018",
        "name": "John Jacobs JJ E14556 C2",
        "style": "oval",
        "colour": "warm_grey",
        "colour_hex": "#968C82",
        "material": "titanium",
        "face_shape_tags": ["round", "square", "oblong"],
        "undertone_tags": ["neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 52,
        "bridge_width_mm": 17,
        "temple_length_mm": 140,
        "vibe_tags": ["minimal", "professional"],
        "retailer": "John Jacobs",
        "price_inr": 6999,
        "buy_url": "https://www.johnjacobs.com/jj-e14556-c2-eyeglasses.html",
        "product_image_url": "https://static.johnjacobs.com/media/catalog/product/jj-e14556-c2.jpg",
    },
    # ── 19. Square | Caramel | Titan Eye+ ─────────────────────────────────
    {
        "frame_id": "11111111-0019-0000-0000-000000000019",
        "name": "Titan Eye+ T6234 C4",
        "style": "square",
        "colour": "caramel",
        "colour_hex": "#C47F41",
        "material": "acetate",
        "face_shape_tags": ["oval", "round"],
        "undertone_tags": ["warm"],
        "gender_tag": "unisex",
        "lens_width_mm": 53,
        "bridge_width_mm": 18,
        "temple_length_mm": 145,
        "vibe_tags": ["retro", "classic"],
        "retailer": "Titan Eye+",
        "price_inr": 2899,
        "buy_url": "https://www.titaneyeplus.com/product/T6234C4",
        "product_image_url": "https://www.titaneyeplus.com/media/catalog/product/T/6/T6234C4.jpg",
    },
    # ── 20. Rimless | Silver | Lenskart ───────────────────────────────────
    {
        "frame_id": "11111111-0020-0000-0000-000000000020",
        "name": "Vincent Chase VC E18123 C3",
        "style": "rimless",
        "colour": "silver",
        "colour_hex": "#C0C0C0",
        "material": "titanium",
        "face_shape_tags": ["oval", "heart", "diamond"],
        "undertone_tags": ["cool", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 52,
        "bridge_width_mm": 15,
        "temple_length_mm": 140,
        "vibe_tags": ["minimal", "professional"],
        "retailer": "Lenskart",
        "price_inr": 3299,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e18123-c3-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e18123-c3.jpg",
    },

    # ══════════════════════════════════════════════════════════════════════
    # Sprint 2 additions — 30 frames filling style × colour coverage gaps
    # Priority: round/wayfarer/browline (most universally useful styles)
    # and tortoiseshell/black/navy (highest undertone coverage colours)
    # ══════════════════════════════════════════════════════════════════════

    # ── 21. Round | Tortoiseshell | Lenskart ──────────────────────────────
    {
        "frame_id": "11111111-0021-0000-0000-000000000021",
        "name": "Vincent Chase VC E19001 C2",
        "style": "round",
        "colour": "tortoiseshell",
        "colour_hex": "#8B5C2A",
        "material": "acetate",
        "face_shape_tags": ["square", "heart", "diamond", "oblong"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 48,
        "bridge_width_mm": 20,
        "temple_length_mm": 145,
        "vibe_tags": ["retro", "editorial"],
        "retailer": "Lenskart",
        "price_inr": 1599,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e19001-c2-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e19001-c2.jpg",
    },
    # ── 22. Wayfarer | Tortoiseshell | Titan Eye+ ─────────────────────────
    {
        "frame_id": "11111111-0022-0000-0000-000000000022",
        "name": "Titan Eye+ T7112 C2",
        "style": "wayfarer",
        "colour": "tortoiseshell",
        "colour_hex": "#7B4F2C",
        "material": "acetate",
        "face_shape_tags": ["oval", "round", "heart", "oblong"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 54,
        "bridge_width_mm": 18,
        "temple_length_mm": 145,
        "vibe_tags": ["classic", "retro"],
        "retailer": "Titan Eye+",
        "price_inr": 2799,
        "buy_url": "https://www.titaneyeplus.com/product/T7112C2",
        "product_image_url": "https://www.titaneyeplus.com/media/catalog/product/T/7/T7112C2.jpg",
    },
    # ── 23. Browline | Black | Lenskart ───────────────────────────────────
    {
        "frame_id": "11111111-0023-0000-0000-000000000023",
        "name": "Vincent Chase VC E19234 C1",
        "style": "browline",
        "colour": "black",
        "colour_hex": "#1A1A1A",
        "material": "mixed",
        "face_shape_tags": ["oval", "round", "diamond", "oblong"],
        "undertone_tags": ["cool", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 52,
        "bridge_width_mm": 18,
        "temple_length_mm": 145,
        "vibe_tags": ["classic", "professional", "bold"],
        "retailer": "Lenskart",
        "price_inr": 1799,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e19234-c1-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e19234-c1.jpg",
    },
    # ── 24. Oval | Brown | John Jacobs ────────────────────────────────────
    {
        "frame_id": "11111111-0024-0000-0000-000000000024",
        "name": "John Jacobs JJ E15678 C3",
        "style": "oval",
        "colour": "brown",
        "colour_hex": "#654321",
        "material": "acetate",
        "face_shape_tags": ["square", "heart", "diamond"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "women",
        "lens_width_mm": 51,
        "bridge_width_mm": 17,
        "temple_length_mm": 140,
        "vibe_tags": ["classic", "professional"],
        "retailer": "John Jacobs",
        "price_inr": 3599,
        "buy_url": "https://www.johnjacobs.com/jj-e15678-c3-eyeglasses.html",
        "product_image_url": "https://static.johnjacobs.com/media/catalog/product/jj-e15678-c3.jpg",
    },
    # ── 25. Rectangular | Black | Ray-Ban ─────────────────────────────────
    {
        "frame_id": "11111111-0025-0000-0000-000000000025",
        "name": "Ray-Ban RB5228 Optical",
        "style": "rectangular",
        "colour": "black",
        "colour_hex": "#1A1A1A",
        "material": "acetate",
        "face_shape_tags": ["oval", "round", "oblong"],
        "undertone_tags": ["cool", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 53,
        "bridge_width_mm": 17,
        "temple_length_mm": 145,
        "vibe_tags": ["classic", "professional"],
        "retailer": "Ray-Ban",
        "price_inr": 10990,
        "buy_url": "https://www.ray-ban.com/en_IN/p/rb5228/RB5228__2000",
        "product_image_url": "https://www.ray-ban.com/media/catalog/product/R/B/RB5228_2000_001_shad_qt.png",
    },
    # ── 26. Browline | Tortoiseshell | Titan Eye+ ─────────────────────────
    {
        "frame_id": "11111111-0026-0000-0000-000000000026",
        "name": "Titan Eye+ T7334 C3",
        "style": "browline",
        "colour": "tortoiseshell",
        "colour_hex": "#8B5C2A",
        "material": "mixed",
        "face_shape_tags": ["oval", "round", "diamond"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 52,
        "bridge_width_mm": 19,
        "temple_length_mm": 145,
        "vibe_tags": ["retro", "classic", "professional"],
        "retailer": "Titan Eye+",
        "price_inr": 3099,
        "buy_url": "https://www.titaneyeplus.com/product/T7334C3",
        "product_image_url": "https://www.titaneyeplus.com/media/catalog/product/T/7/T7334C3.jpg",
    },
    # ── 27. Cat-eye | Black | Lenskart ────────────────────────────────────
    {
        "frame_id": "11111111-0027-0000-0000-000000000027",
        "name": "John Jacobs JJ E16001 C1",
        "style": "cat-eye",
        "colour": "black",
        "colour_hex": "#1A1A1A",
        "material": "acetate",
        "face_shape_tags": ["square", "diamond"],
        "undertone_tags": ["cool", "neutral"],
        "gender_tag": "women",
        "lens_width_mm": 50,
        "bridge_width_mm": 18,
        "temple_length_mm": 140,
        "vibe_tags": ["editorial", "bold", "professional"],
        "retailer": "John Jacobs",
        "price_inr": 3899,
        "buy_url": "https://www.johnjacobs.com/jj-e16001-c1-eyeglasses.html",
        "product_image_url": "https://static.johnjacobs.com/media/catalog/product/jj-e16001-c1.jpg",
    },
    # ── 28. Round | Brown | Titan Eye+ ────────────────────────────────────
    {
        "frame_id": "11111111-0028-0000-0000-000000000028",
        "name": "Titan Eye+ T8002 C4",
        "style": "round",
        "colour": "brown",
        "colour_hex": "#654321",
        "material": "acetate",
        "face_shape_tags": ["square", "heart", "diamond", "oblong"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 49,
        "bridge_width_mm": 19,
        "temple_length_mm": 145,
        "vibe_tags": ["retro", "classic"],
        "retailer": "Titan Eye+",
        "price_inr": 2399,
        "buy_url": "https://www.titaneyeplus.com/product/T8002C4",
        "product_image_url": "https://www.titaneyeplus.com/media/catalog/product/T/8/T8002C4.jpg",
    },
    # ── 29. Aviator | Silver | Ray-Ban ────────────────────────────────────
    {
        "frame_id": "11111111-0029-0000-0000-000000000029",
        "name": "Ray-Ban RB3025 Aviator Silver",
        "style": "aviator",
        "colour": "silver",
        "colour_hex": "#C0C0C0",
        "material": "metal",
        "face_shape_tags": ["oval", "heart"],
        "undertone_tags": ["cool", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 58,
        "bridge_width_mm": 14,
        "temple_length_mm": 135,
        "vibe_tags": ["classic", "bold"],
        "retailer": "Ray-Ban",
        "price_inr": 9490,
        "buy_url": "https://www.ray-ban.com/en_IN/p/rb3025/RB3025__W3277",
        "product_image_url": "https://www.ray-ban.com/media/catalog/product/R/B/RB3025_W3277_001_shad_qt.png",
    },
    # ── 30. Oval | Black | Lenskart ───────────────────────────────────────
    {
        "frame_id": "11111111-0030-0000-0000-000000000030",
        "name": "Vincent Chase VC E20001 C1",
        "style": "oval",
        "colour": "black",
        "colour_hex": "#1A1A1A",
        "material": "metal",
        "face_shape_tags": ["square", "heart", "diamond"],
        "undertone_tags": ["cool", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 51,
        "bridge_width_mm": 17,
        "temple_length_mm": 140,
        "vibe_tags": ["minimal", "professional"],
        "retailer": "Lenskart",
        "price_inr": 1999,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e20001-c1-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e20001-c1.jpg",
    },
    # ── 31. Rimless | Gold | John Jacobs ──────────────────────────────────
    {
        "frame_id": "11111111-0031-0000-0000-000000000031",
        "name": "John Jacobs JJ E16234 C2",
        "style": "rimless",
        "colour": "gold",
        "colour_hex": "#C8A000",
        "material": "titanium",
        "face_shape_tags": ["heart", "diamond"],
        "undertone_tags": ["warm"],
        "gender_tag": "unisex",
        "lens_width_mm": 50,
        "bridge_width_mm": 16,
        "temple_length_mm": 140,
        "vibe_tags": ["minimal", "professional"],
        "retailer": "John Jacobs",
        "price_inr": 5499,
        "buy_url": "https://www.johnjacobs.com/jj-e16234-c2-eyeglasses.html",
        "product_image_url": "https://static.johnjacobs.com/media/catalog/product/jj-e16234-c2.jpg",
    },
    # ── 32. Browline | Navy | Lenskart ────────────────────────────────────
    {
        "frame_id": "11111111-0032-0000-0000-000000000032",
        "name": "Vincent Chase VC E20112 C5",
        "style": "browline",
        "colour": "navy",
        "colour_hex": "#001F5B",
        "material": "mixed",
        "face_shape_tags": ["oval", "round", "diamond", "oblong"],
        "undertone_tags": ["cool"],
        "gender_tag": "men",
        "lens_width_mm": 53,
        "bridge_width_mm": 18,
        "temple_length_mm": 145,
        "vibe_tags": ["classic", "professional"],
        "retailer": "Lenskart",
        "price_inr": 1899,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e20112-c5-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e20112-c5.jpg",
    },
    # ── 33. Wayfarer | Amber | Titan Eye+ ─────────────────────────────────
    {
        "frame_id": "11111111-0033-0000-0000-000000000033",
        "name": "Titan Eye+ T8223 C6",
        "style": "wayfarer",
        "colour": "amber",
        "colour_hex": "#C89600",
        "material": "acetate",
        "face_shape_tags": ["oval", "round", "heart", "oblong"],
        "undertone_tags": ["warm"],
        "gender_tag": "unisex",
        "lens_width_mm": 54,
        "bridge_width_mm": 18,
        "temple_length_mm": 145,
        "vibe_tags": ["retro", "bold"],
        "retailer": "Titan Eye+",
        "price_inr": 2599,
        "buy_url": "https://www.titaneyeplus.com/product/T8223C6",
        "product_image_url": "https://www.titaneyeplus.com/media/catalog/product/T/8/T8223C6.jpg",
    },
    # ── 34. Rectangular | Brown | Lenskart ────────────────────────────────
    {
        "frame_id": "11111111-0034-0000-0000-000000000034",
        "name": "Vincent Chase VC E20345 C4",
        "style": "rectangular",
        "colour": "brown",
        "colour_hex": "#654321",
        "material": "acetate",
        "face_shape_tags": ["oval", "round", "oblong"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 53,
        "bridge_width_mm": 17,
        "temple_length_mm": 140,
        "vibe_tags": ["classic", "professional"],
        "retailer": "Lenskart",
        "price_inr": 1699,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e20345-c4-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e20345-c4.jpg",
    },
    # ── 35. Cat-eye | Tortoiseshell | John Jacobs ─────────────────────────
    {
        "frame_id": "11111111-0035-0000-0000-000000000035",
        "name": "John Jacobs JJ E16789 C2",
        "style": "cat-eye",
        "colour": "tortoiseshell",
        "colour_hex": "#8B5C2A",
        "material": "acetate",
        "face_shape_tags": ["square", "diamond"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "women",
        "lens_width_mm": 50,
        "bridge_width_mm": 18,
        "temple_length_mm": 140,
        "vibe_tags": ["retro", "editorial", "bold"],
        "retailer": "John Jacobs",
        "price_inr": 4199,
        "buy_url": "https://www.johnjacobs.com/jj-e16789-c2-eyeglasses.html",
        "product_image_url": "https://static.johnjacobs.com/media/catalog/product/jj-e16789-c2.jpg",
    },
    # ── 36. Oval | Navy | Lenskart ────────────────────────────────────────
    {
        "frame_id": "11111111-0036-0000-0000-000000000036",
        "name": "Vincent Chase VC E20456 C6",
        "style": "oval",
        "colour": "navy",
        "colour_hex": "#001F5B",
        "material": "metal",
        "face_shape_tags": ["square", "heart", "diamond"],
        "undertone_tags": ["cool"],
        "gender_tag": "unisex",
        "lens_width_mm": 51,
        "bridge_width_mm": 17,
        "temple_length_mm": 140,
        "vibe_tags": ["professional", "minimal"],
        "retailer": "Lenskart",
        "price_inr": 2299,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e20456-c6-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e20456-c6.jpg",
    },
    # ── 37. Browline | Silver | Titan Eye+ ────────────────────────────────
    {
        "frame_id": "11111111-0037-0000-0000-000000000037",
        "name": "Titan Eye+ T8456 C1",
        "style": "browline",
        "colour": "silver",
        "colour_hex": "#C0C0C0",
        "material": "metal",
        "face_shape_tags": ["oval", "round", "diamond"],
        "undertone_tags": ["cool", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 52,
        "bridge_width_mm": 19,
        "temple_length_mm": 145,
        "vibe_tags": ["minimal", "professional"],
        "retailer": "Titan Eye+",
        "price_inr": 2899,
        "buy_url": "https://www.titaneyeplus.com/product/T8456C1",
        "product_image_url": "https://www.titaneyeplus.com/media/catalog/product/T/8/T8456C1.jpg",
    },
    # ── 38. Round | Navy | Lenskart ───────────────────────────────────────
    {
        "frame_id": "11111111-0038-0000-0000-000000000038",
        "name": "Vincent Chase VC E20567 C6",
        "style": "round",
        "colour": "navy",
        "colour_hex": "#001F5B",
        "material": "acetate",
        "face_shape_tags": ["square", "heart", "diamond", "oblong"],
        "undertone_tags": ["cool"],
        "gender_tag": "unisex",
        "lens_width_mm": 49,
        "bridge_width_mm": 20,
        "temple_length_mm": 145,
        "vibe_tags": ["retro", "bold"],
        "retailer": "Lenskart",
        "price_inr": 1799,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e20567-c6-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e20567-c6.jpg",
    },
    # ── 39. Wayfarer | Brown | Titan Eye+ ─────────────────────────────────
    {
        "frame_id": "11111111-0039-0000-0000-000000000039",
        "name": "Titan Eye+ T8678 C4",
        "style": "wayfarer",
        "colour": "brown",
        "colour_hex": "#654321",
        "material": "acetate",
        "face_shape_tags": ["oval", "round", "heart", "oblong"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 54,
        "bridge_width_mm": 18,
        "temple_length_mm": 145,
        "vibe_tags": ["classic", "retro"],
        "retailer": "Titan Eye+",
        "price_inr": 2699,
        "buy_url": "https://www.titaneyeplus.com/product/T8678C4",
        "product_image_url": "https://www.titaneyeplus.com/media/catalog/product/T/8/T8678C4.jpg",
    },
    # ── 40. Rimless | Navy | Lenskart ─────────────────────────────────────
    {
        "frame_id": "11111111-0040-0000-0000-000000000040",
        "name": "Vincent Chase VC E20678 C6",
        "style": "rimless",
        "colour": "navy",
        "colour_hex": "#001F5B",
        "material": "titanium",
        "face_shape_tags": ["heart", "diamond"],
        "undertone_tags": ["cool"],
        "gender_tag": "unisex",
        "lens_width_mm": 50,
        "bridge_width_mm": 16,
        "temple_length_mm": 140,
        "vibe_tags": ["minimal", "professional"],
        "retailer": "Lenskart",
        "price_inr": 2699,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e20678-c6-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e20678-c6.jpg",
    },
    # ── 41. Aviator | Gunmetal | John Jacobs ──────────────────────────────
    {
        "frame_id": "11111111-0041-0000-0000-000000000041",
        "name": "John Jacobs JJ E17001 C5",
        "style": "aviator",
        "colour": "gunmetal",
        "colour_hex": "#545E6B",
        "material": "metal",
        "face_shape_tags": ["oval", "heart"],
        "undertone_tags": ["cool"],
        "gender_tag": "men",
        "lens_width_mm": 57,
        "bridge_width_mm": 14,
        "temple_length_mm": 135,
        "vibe_tags": ["bold", "sporty", "editorial"],
        "retailer": "John Jacobs",
        "price_inr": 4599,
        "buy_url": "https://www.johnjacobs.com/jj-e17001-c5-eyeglasses.html",
        "product_image_url": "https://static.johnjacobs.com/media/catalog/product/jj-e17001-c5.jpg",
    },
    # ── 42. Cat-eye | Rose Gold | John Jacobs ─────────────────────────────
    {
        "frame_id": "11111111-0042-0000-0000-000000000042",
        "name": "John Jacobs JJ E17112 C3",
        "style": "cat-eye",
        "colour": "rose_gold",
        "colour_hex": "#B76E79",
        "material": "metal",
        "face_shape_tags": ["square", "diamond"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "women",
        "lens_width_mm": 50,
        "bridge_width_mm": 17,
        "temple_length_mm": 140,
        "vibe_tags": ["editorial", "minimal"],
        "retailer": "John Jacobs",
        "price_inr": 4899,
        "buy_url": "https://www.johnjacobs.com/jj-e17112-c3-eyeglasses.html",
        "product_image_url": "https://static.johnjacobs.com/media/catalog/product/jj-e17112-c3.jpg",
    },
    # ── 43. Rectangular | Navy | Titan Eye+ ───────────────────────────────
    {
        "frame_id": "11111111-0043-0000-0000-000000000043",
        "name": "Titan Eye+ T8890 C6",
        "style": "rectangular",
        "colour": "navy",
        "colour_hex": "#001F5B",
        "material": "acetate",
        "face_shape_tags": ["oval", "round", "oblong"],
        "undertone_tags": ["cool", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 54,
        "bridge_width_mm": 17,
        "temple_length_mm": 145,
        "vibe_tags": ["classic", "professional"],
        "retailer": "Titan Eye+",
        "price_inr": 2999,
        "buy_url": "https://www.titaneyeplus.com/product/T8890C6",
        "product_image_url": "https://www.titaneyeplus.com/media/catalog/product/T/8/T8890C6.jpg",
    },
    # ── 44. Round | Warm Grey | Lenskart ──────────────────────────────────
    {
        "frame_id": "11111111-0044-0000-0000-000000000044",
        "name": "Vincent Chase VC E21001 C2",
        "style": "round",
        "colour": "warm_grey",
        "colour_hex": "#968C82",
        "material": "titanium",
        "face_shape_tags": ["square", "oblong"],
        "undertone_tags": ["neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 49,
        "bridge_width_mm": 19,
        "temple_length_mm": 145,
        "vibe_tags": ["minimal", "professional"],
        "retailer": "Lenskart",
        "price_inr": 3199,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e21001-c2-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e21001-c2.jpg",
    },
    # ── 45. Geometric | Navy | Titan Eye+ ─────────────────────────────────
    {
        "frame_id": "11111111-0045-0000-0000-000000000045",
        "name": "Titan Eye+ T9001 C6",
        "style": "geometric",
        "colour": "navy",
        "colour_hex": "#001F5B",
        "material": "metal",
        "face_shape_tags": ["oval", "round"],
        "undertone_tags": ["cool"],
        "gender_tag": "unisex",
        "lens_width_mm": 52,
        "bridge_width_mm": 18,
        "temple_length_mm": 145,
        "vibe_tags": ["editorial", "bold", "minimal"],
        "retailer": "Titan Eye+",
        "price_inr": 3399,
        "buy_url": "https://www.titaneyeplus.com/product/T9001C6",
        "product_image_url": "https://www.titaneyeplus.com/media/catalog/product/T/9/T9001C6.jpg",
    },
    # ── 46. Oval | Tortoiseshell | Titan Eye+ ─────────────────────────────
    {
        "frame_id": "11111111-0046-0000-0000-000000000046",
        "name": "Titan Eye+ T9112 C2",
        "style": "oval",
        "colour": "tortoiseshell",
        "colour_hex": "#7B4F2C",
        "material": "acetate",
        "face_shape_tags": ["square", "heart", "diamond"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "women",
        "lens_width_mm": 51,
        "bridge_width_mm": 17,
        "temple_length_mm": 140,
        "vibe_tags": ["classic", "editorial"],
        "retailer": "Titan Eye+",
        "price_inr": 2799,
        "buy_url": "https://www.titaneyeplus.com/product/T9112C2",
        "product_image_url": "https://www.titaneyeplus.com/media/catalog/product/T/9/T9112C2.jpg",
    },
    # ── 47. Wayfarer | Rose Gold | Lenskart ───────────────────────────────
    {
        "frame_id": "11111111-0047-0000-0000-000000000047",
        "name": "Vincent Chase VC E21234 C3",
        "style": "wayfarer",
        "colour": "rose_gold",
        "colour_hex": "#B76E79",
        "material": "mixed",
        "face_shape_tags": ["oval", "round", "heart", "oblong"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "women",
        "lens_width_mm": 53,
        "bridge_width_mm": 18,
        "temple_length_mm": 140,
        "vibe_tags": ["minimal", "editorial"],
        "retailer": "Lenskart",
        "price_inr": 1999,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e21234-c3-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e21234-c3.jpg",
    },
    # ── 48. Square | Black | Lenskart ─────────────────────────────────────
    {
        "frame_id": "11111111-0048-0000-0000-000000000048",
        "name": "Vincent Chase VC E21345 C1",
        "style": "square",
        "colour": "black",
        "colour_hex": "#1A1A1A",
        "material": "acetate",
        "face_shape_tags": ["oval", "round"],
        "undertone_tags": ["cool", "neutral"],
        "gender_tag": "men",
        "lens_width_mm": 54,
        "bridge_width_mm": 17,
        "temple_length_mm": 145,
        "vibe_tags": ["bold", "professional"],
        "retailer": "Lenskart",
        "price_inr": 1599,
        "buy_url": "https://www.lenskart.com/vincent-chase-vc-e21345-c1-eyeglasses.html",
        "product_image_url": "https://static.lenskart.com/media/catalog/product/v/c/vc-e21345-c1.jpg",
    },
    # ── 49. Rimless | Brown | John Jacobs ─────────────────────────────────
    {
        "frame_id": "11111111-0049-0000-0000-000000000049",
        "name": "John Jacobs JJ E17456 C4",
        "style": "rimless",
        "colour": "brown",
        "colour_hex": "#654321",
        "material": "titanium",
        "face_shape_tags": ["heart", "diamond"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "unisex",
        "lens_width_mm": 50,
        "bridge_width_mm": 16,
        "temple_length_mm": 140,
        "vibe_tags": ["minimal", "professional"],
        "retailer": "John Jacobs",
        "price_inr": 5299,
        "buy_url": "https://www.johnjacobs.com/jj-e17456-c4-eyeglasses.html",
        "product_image_url": "https://static.johnjacobs.com/media/catalog/product/jj-e17456-c4.jpg",
    },
    # ── 50. Aviator | Rose Gold | John Jacobs ─────────────────────────────
    {
        "frame_id": "11111111-0050-0000-0000-000000000050",
        "name": "John Jacobs JJ E17567 C3",
        "style": "aviator",
        "colour": "rose_gold",
        "colour_hex": "#B76E79",
        "material": "metal",
        "face_shape_tags": ["oval", "heart"],
        "undertone_tags": ["warm", "neutral"],
        "gender_tag": "women",
        "lens_width_mm": 57,
        "bridge_width_mm": 14,
        "temple_length_mm": 135,
        "vibe_tags": ["editorial", "classic"],
        "retailer": "John Jacobs",
        "price_inr": 5199,
        "buy_url": "https://www.johnjacobs.com/jj-e17567-c3-eyeglasses.html",
        "product_image_url": "https://static.johnjacobs.com/media/catalog/product/jj-e17567-c3.jpg",
    },
]


def insert_seed_frames(dry_run: bool = False) -> None:
    if dry_run:
        print(f"[dry-run] Would insert {len(SEED_FRAMES)} frames:")
        for f in SEED_FRAMES:
            print(f"  {f['name']:45s} | {f['style']:12s} | {f['colour']:15s} | {f['retailer']}")
        return

    from supabase import create_client
    import os
    supabase_url = os.environ["SUPABASE_URL"]
    supabase_key = os.environ["SUPABASE_SERVICE_KEY"]
    client = create_client(supabase_url, supabase_key)

    result = client.table("frames").upsert(SEED_FRAMES, on_conflict="frame_id").execute()
    inserted = len(result.data) if result.data else 0
    print(f"Inserted/updated {inserted} seed frames.")


if __name__ == "__main__":
    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).parent.parent))

    # Load .env from backend/
    from dotenv import load_dotenv
    load_dotenv(dotenv_path=Path(__file__).parent.parent / ".env")

    parser = argparse.ArgumentParser(description="Seed test frames into Supabase")
    parser.add_argument("--dry-run", action="store_true", help="Print without inserting")
    args = parser.parse_args()

    insert_seed_frames(dry_run=args.dry_run)
